"""Pure, device-free PLC learning models and first-answer sessions."""
from dataclasses import dataclass, field
from uuid import uuid4

BOOK_ID = "electrical_control_plc_s71200_tong"
SAFETY = "仅限抽象教学模拟；不连接设备，不表示实际接线、扫描时序或设备动作。"
SCAN_NOTE = ("这里以读取输入为教学周期起点：读取快照 → 执行逻辑 → 更新显示。"
             "真实CPU还涉及过程映像、输出更新、通信和中断；不能据此推断实际响应时间。")
SOURCE_URL = "https://docs.tia.siemens.cloud/r/simatic_s7_1200_manual_collection_enus_20/plc-concepts/execution-of-the-user-program/processing-the-scan-cycle-in-run-mode"


def logic_output(operator, a, b=False):
    if operator == "AND":
        return bool(a and b)
    if operator == "OR":
        return bool(a or b)
    if operator == "NOT":
        return not a
    raise ValueError("未知逻辑")


def hold_next(allow, stop, start, previous):
    return bool(allow and not stop and (start or previous))


@dataclass
class ScanModel:
    phase: int = 0
    sampled: bool = False
    computed: bool = False
    output: bool = False
    cycles: int = 0

    def step(self, live_input):
        if self.phase == 0:
            self.sampled = bool(live_input)
        elif self.phase == 1:
            self.computed = self.sampled
        else:
            self.output = self.computed
            self.cycles += 1
        self.phase = (self.phase + 1) % 3


LABS = {
    "logic": {"title": "与、或、非：输入怎样决定结果", "unit": 4,
              "card": "plc_logic_structure", "goal": "比较AND、OR、NOT，并用输入条件解释结果。"},
    "scan": {"title": "扫描过程：输入变化何时生效", "unit": 4,
             "card": "plc_program_cycle", "goal": "读取后改变输入，观察本轮快照与下一轮的区别。"},
    "hold": {"title": "启动、保持与停止优先", "unit": 6,
             "card": "plc_project_flow", "goal": "观察启动请求消失后的保持，以及停止、许可条件的优先作用。"},
}


def question_specs():
    """Answers are generated by the same rules used in the playground."""
    snapshot = ScanModel()
    snapshot.step(False)
    snapshot.step(True)
    snapshot.step(True)
    first_cycle_result = snapshot.output
    for _ in range(3):
        snapshot.step(True)
    rows = (
        ("logic", "predict", "AND逻辑中A为真、B为假，结果是什么？", logic_output("AND", True, False), "AND要求两个条件同时为真。"),
        ("logic", "transfer", "OR逻辑中A为假、B为真，结果是什么？", logic_output("OR", False, True), "OR只要求至少一个条件为真。"),
        ("scan", "predict", "读取到假后，输入才变真。本简化模型本轮更新结果是什么？", first_cycle_result, "执行使用本轮已读取的快照，不追随读取后的输入变化。"),
        ("scan", "transfer", "输入保持为真，下一轮重新读取并完成执行、更新后，结果是什么？", snapshot.output, "下一轮重新读取，新的输入条件才进入本模型的计算。"),
        ("hold", "predict", "许可为真、停止为假，已运行且启动请求撤回，下一步运行状态是什么？", hold_next(True, False, False, True), "先前运行状态可维持保持分支。"),
        ("hold", "transfer", "许可为真，启动和停止请求同时为真，下一步运行状态是什么？", hold_next(True, True, True, True), "本模型中停止优先；停止条件阻断启动与保持两条路径。"),
    )
    return tuple({"id": f"plc_{lab}_{kind}", "chapter_id": f"plc_lab_{lab}",
                  "stem": stem, "options": ("真", "假"), "answer": "真" if answer else "假",
                  "explanation": explanation, "knowledge_point": LABS[lab]["title"],
                  "card": LABS[lab]["card"]} for lab, kind, stem, answer, explanation in rows)


@dataclass
class LabSession:
    lab_id: str
    session_id: str = field(default_factory=lambda: uuid4().hex)
    phase: str = "intro"
    answers: dict = field(default_factory=dict)
    observations: int = 0
    scan: ScanModel = field(default_factory=ScanModel)
    running: bool = False
    last_observation: str = ""
    record: object = None

    def __post_init__(self):
        if self.lab_id not in LABS:
            raise ValueError("未知互动训练")

    def begin(self):
        if self.phase == "intro":
            self.phase = "predict"

    def answer(self, selected):
        from .quiz import QUESTION_MAP, QuizAnswer
        if self.phase not in {"predict", "transfer"}:
            raise ValueError("当前不是作答阶段")
        q = QUESTION_MAP[f"plc_{self.lab_id}_{self.phase}"]
        if selected not in (*q.options, "不确定"):
            raise ValueError("请选择有效答案")
        self.answers.setdefault(q.id, QuizAnswer(q.id, selected, q.answer,
                                                selected == q.answer, selected == "不确定"))
        self.phase = "observe" if self.phase == "predict" else "report"

    def observe(self, *, operator="AND", a=False, b=False, allow=True, stop=False, start=False):
        if self.phase != "observe":
            raise ValueError("请先完成预测")
        if self.lab_id == "logic":
            result = logic_output(operator, a, b)
            self.last_observation = f"{operator}：A={a}，B={b if operator != 'NOT' else '不参与'} → 结果={result}"
        elif self.lab_id == "scan":
            phase = ("读取快照", "执行逻辑", "更新显示")[self.scan.phase]
            self.scan.step(a)
            result = self.scan.output
            self.last_observation = f"已完成：{phase}；当前输入={a}；快照={self.scan.sampled}；计算值={self.scan.computed}；显示结果={result}"
        else:
            previous = self.running
            self.running = hold_next(allow, stop, start, previous)
            result = self.running
            self.last_observation = f"许可={allow}，停止={stop}，启动={start}，先前运行={previous} → 运行={result}"
        self.observations += 1
        return result

    def finish_observation(self):
        if self.phase != "observe" or not self.observations or (self.lab_id == "scan" and not self.scan.cycles):
            raise ValueError("请至少完成一次观察；扫描训练需完成一个周期")
        self.phase = "transfer"

    def to_record(self):
        from .quiz import make_quiz_record
        if self.phase != "report" or len(self.answers) != 2:
            raise ValueError("请完成预测、观察和迁移题")
        if self.record is None:
            self.record = make_quiz_record(f"plc_lab_{self.lab_id}", tuple(self.answers.values()),
                                          mode="plc_lab", quiz_id=self.session_id)
        return self.record

    def report_text(self):
        from .quiz import QUESTION_MAP
        record = self.to_record()
        lines = [LABS[self.lab_id]["title"], SAFETY, f"首次判断：{record.correct_count}/2",
                 "自由操作不计分；本成绩不改变单元测验通过状态。"]
        for answer in record.answers:
            q = QUESTION_MAP[answer.question_id]
            lines.extend([q.stem, f"首次选择：{answer.selected_answer}；正确答案：{q.answer}", q.explanation])
        lines.extend(["最近一次观察：" + self.last_observation, "关联知识卡：" + LABS[self.lab_id]["card"],
                      "来源：Siemens S7-1200手册；抽象教学路径：部分核对。", SOURCE_URL])
        return "\n".join(lines)
